import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.js',
        './resources/js/**/*.vue',
        './app/Http/Controllers/**/*.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                'elegant-blue': {
                    50: '#eff6ff',
                    100: '#dbeafe',
                    200: '#bfdbfe',
                    300: '#93c5fd',
                    400: '#60a5fa',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                    800: '#1e40af',
                    900: '#1e3a8a',
                    950: '#172554',
                },
                'light-gray': {
                    50: '#f8fafc',
                    100: '#f1f5f9',
                    200: '#e2e8f0',
                    300: '#cbd5e1',
                    400: '#94a3b8',
                    500: '#64748b',
                    600: '#475569',
                    700: '#334155',
                    800: '#1e293b',
                    900: '#0f172a',
                    950: '#020617',
                },
                'white': '#ffffff',
            },
            fontSize: {
                'xs': ['0.75rem', { lineHeight: '1.25rem', fontWeight: '300' }],
                'sm': ['0.875rem', { lineHeight: '1.5rem', fontWeight: '300' }],
                'base': ['1rem', { lineHeight: '1.75rem', fontWeight: '300' }],
                'lg': ['1.125rem', { lineHeight: '1.75rem', fontWeight: '400' }],
                'xl': ['1.25rem', { lineHeight: '2rem', fontWeight: '700' }],
                '2xl': ['1.5rem', { lineHeight: '2.25rem', fontWeight: '700' }],
                '3xl': ['1.875rem', { lineHeight: '2.5rem', fontWeight: '700' }],
                '4xl': ['2.25rem', { lineHeight: '2.75rem', fontWeight: '700' }],
                '5xl': ['3rem', { lineHeight: '1', fontWeight: '700' }],
                '6xl': ['3.75rem', { lineHeight: '1', fontWeight: '700' }],
                '7xl': ['4.5rem', { lineHeight: '1', fontWeight: '700' }],
                '8xl': ['6rem', { lineHeight: '1', fontWeight: '700' }],
                '9xl': ['8rem', { lineHeight: '1', fontWeight: '700' }],
            },
            spacing: {
                '0': '0',
                '1': '0.25rem',
                '2': '0.5rem',
                '3': '0.75rem',
                '4': '1rem',
                '5': '1.25rem',
                '6': '1.5rem',
                '7': '1.75rem',
                '8': '2rem',
                '9': '2.25rem',
                '10': '2.5rem',
                '11': '2.75rem',
                '12': '3rem',
                '14': '3.5rem',
                '16': '4rem',
                '20': '5rem',
                '24': '6rem',
                '28': '7rem',
                '32': '8rem',
                '36': '9rem',
                '40': '10rem',
                '44': '11rem',
                '48': '12rem',
                '52': '13rem',
                '56': '14rem',
                '60': '15rem',
                '64': '16rem',
                '72': '18rem',
                '80': '20rem',
                '96': '24rem',
            },
            animation: {
                'fade-in': 'fadeIn 0.8s ease-out forwards',
                'fade-in-slow': 'fadeIn 1.2s ease-out forwards',
                'fade-in-fast': 'fadeIn 0.5s ease-out forwards',
                'scale-in': 'scaleIn 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
                'float': 'float 6s ease-in-out infinite',
                'shimmer': 'shimmer 1.5s linear infinite',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                scaleIn: {
                    '0%': { opacity: '0', transform: 'scale(0.9)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
                float: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-20px)' },
                },
                shimmer: {
                    '0%': { backgroundPosition: '-200% 0' },
                    '100%': { backgroundPosition: '200% 0' },
                },
            },
        },
    },

    plugins: [forms],
};
